repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.5.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        language_version: python3.6
        args:
          [
            -ll,
            "-x=node_modules,tests",
            "-s=B101,B301,B403,B308,B303,B608",
            "-b=bandit_baseline.json",
          ]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.8.1
    hooks:
      - id: eslint
        args: ["--ext=.js,.vue"]
        files: (.+\.js$)|(.+\.vue$)
        types: ["file"]
        additional_dependencies:
          - babel-eslint
          - eslint
          - eslint-config-prettier
          - eslint-plugin-import
          - eslint-plugin-jest
          - eslint-plugin-node
          - eslint-plugin-prettier
          - eslint-plugin-promise
          - eslint-plugin-standard
          - eslint-plugin-unicorn
          - eslint-plugin-vue
          - eslint-plugin-simple-import-sort
          - prettier
          - vue-eslint-parser
  - repo: git@github.com:humitos/mirrors-autoflake.git
    rev: v1.1
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-unused-variables",
          ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
      - id: check-json
        exclude: (\.jshintrc)
      - id: check-yaml
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: end-of-file-fixer
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        name: Flake8 Py3
        additional_dependencies: [flake8-docstrings]
        language_version: python3.6
  - repo: https://github.com/Yelp/detect-secrets
    rev: v0.14.3
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: .*/tests/.*|
